spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    test:
      url: jdbc:postgresql://localhost:5432/testbase
      username: ivan
      password: ivan
      driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


job:
  schedules: ${MY_TABLE_SERVICE_JOB_SCHEDULES:10000}
  cron:
    "0 0 23 * * *"
server:
  port: 8675
  error:
    whitelabel:
      enabled: false
  max-http-header-size: 400
  connection-timeout: 5s



