spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


server:
  port: 8675
  error:
    whitelabel:
      enabled: false
  max-http-header-size: 400
  connection-timeout: 5s



